export const levelNames = [
  "The Whispering Glade",
  "Goblin's Gulch",
  "The Forgotten Path",
  "Sunken Keep Entrance",
  "Crystal Vein Cavern",
  "The Mossy Steps",
  "Batwing Abyss",
  "Spiky Slime Swamp",
  "The Crumbling Bridge",
  "Ancient Ramparts",
  "Elderwood Ascent",
  "The Glimmering Mines",
  "Fools' Leap Chasm",
  "Citadel of the First King",
  "Skyfire Spire's Base",
  "The Haunted Armory",
  "Echoing Halls",
  "The Dragon's Tooth",
  "Grave of the Giants",
  "The Shifting Sands",
  "Cinderfall Passage",
  "The Obsidian Labyrinth",
  "Thornwood Thicket",
  "The Sunless Sanctum",
  "The Howling Peaks",
  "Azure Depths",
  "The Serpent's Coil",
  "Ruins of the Sky Palace",
  "The Shadowed Fen",
  "The Titan's Gauntlet",
  "Whisperwind Cliffs",
  "The Molten Heart",
  "Glacial Crevasse",
  "The Verdant Maze",
  "The Necromancer's Trench",
  "Starlight Alcove",
  "The Clockwork Tower",
  "Wyvern's Roost",
  "The Sunken City",
  "The Prismatic Core",
  "The Endless Stair",
  "The Forlorn Monastery",
  "The Crystal Forest",
  "Heart of the Mountain",
  "The Weeping Chasm",
  "The Celestial Orrery",
  "The Alchemist's Folly",
  "The Abyssal Gate",
  "The Timeless Vault",
  "Throne of the Elf King",
];
